The damn counters
dbuendia/contadores pull request #4
Opened 2022-09-03 19:20 UTC by dbuendia

- They work.
- Please why `setCount(count++)` doesn't work? I don't get it. It makes me click twice to update the value.

![WhatsApp Image 2022-09-03 at 7 38 21 PM](https://user-images.githubusercontent.com/14167326/188285026-aade1f9a-610b-427a-9357-608221369d1a.jpeg)

2022-09-03 20:56 UTC, havebeeair requested changes

2022-09-03 20:56 UTC, havebeeair commented on src/components/Counter.jsx
> +    // Why count++ doesn't work!?
You tell me. Do some research about this and we'll have a discussion about it.

2022-09-04 07:48 UTC, dbuendia commented on src/components/Counter.jsx
> +    // Why count++ doesn't work!?
```suggestion
    Approve my PR
```

2022-09-04 08:21 UTC, dbuendia commented on src/components/Counter.jsx
> +    // Why count++ doesn't work!?
Ok, por lo que veo count++ devuelve el estado inicial de count y luego le suma +1. Pero sigo sin entender por qué habría que hacer doble click (más allá de la primera vez).

Debería ser así, ¿no?

Count = 0; (Click - UI muestra: 0)
Count++ (Click - UI muestra: 0) Count = 1;
Count++ (Click - UI muestra: 1) Count = 2;
Count++ (Click - UI muestra: 2) Count = 3

Sin embargo veo:
Count = 0; (Click - UI muestra: 0)
Count++ (Click - UI muestra: 0)
Count++ (Click - UI muestra: 1) 
Count++ (Click - UI muestra: 1) 
Count++ (Click - UI muestra: 2) 
Count++ (Click - UI muestra: 2), etc.

2022-09-04 08:47 UTC, havebeeair commented on src/components/Counter.jsx
> +    // Why count++ doesn't work!?
Siento que todavía no damos con la respuesta. Te pediría seguir investigando hasta que demos con un por qué. Quiero que practiquemos como usamos google ante este tipo de escenarios.

2022-09-05 12:43 UTC, havebeeair approved these changes

2022-09-05 12:45 UTC, merged